version: '2'
services:
  client:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - clinical-service
    depends_on:
      - api
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - clinical-service
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_ROOT_PASSWORD: admin
      POSTGRES_DB: clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - clinical-service
networks:
  clinical-service:
    driver: bridge